CREATE TABLE SETTLEMN.SS_3BB_VDO_TEMP (
  INVOICENO VARCHAR2(30) NOT NULL,
  BILL_MM VARCHAR2(2) NOT NULL,
  BILL_YY VARCHAR2(4) NOT NULL,
  INV_DATE DATE,
  EVENT_SEQ NUMBER(2,0) NOT NULL,
  PACKATE_NAME VARCHAR2(60) NOT NULL,
  INVOICEMNY NUMBER(18,6),
  PACKAGE_PRICE NUMBER(18,6),
  ADJDISCMNY NUMBER(18,6),
  ADJOTHERMNY NUMBER(18,6),
  VAS_EXC_VAT NUMBER(18,6) NOT NULL,
  VAT_MNY NUMBER(18,6),
  VAS_MNY NUMBER(18,6),
  ACCOUNT_NO VARCHAR2(50) NOT NULL,
  BILLPERIOD VARCHAR2(22) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  USER_DTM DATE,
  USER_ID VARCHAR2(50),
  CDR_FILENAME VARCHAR2(300),
  CDR_STATUS VARCHAR2(50),
  CDR_ID VARCHAR2(22),
  EVENT_TIME DATE,
  ZONE_NAME VARCHAR2(50)
);

CREATE OR REPLACE PUBLIC SYNONYM SS_3BB_VDO_TEMP FOR SETTLEMN.SS_3BB_VDO_TEMP;

GRANT select, insert, update, delete on SETTLEMN.SS_3BB_VDO_TEMP to SS_ADMIN;
GRANT select on SETTLEMN.SS_3BB_VDO_TEMP to SS_QUERY;

CREATE INDEX IDX1_SS_3BB_VDO_TEMP on SS_3BB_VDO_TEMP (INVOICENO ASC, START_DATE ASC);
CREATE INDEX IDX2_SS_3BB_VDO_TEMP on SS_3BB_VDO_TEMP (PACKATE_NAME ASC);