CREATE TABLE SETTLEMN.SS_3BB_VDO (
  INVOICENO VARCHAR2(30) NOT NULL,
  BILL_MM VARCHAR2(2) NOT NULL,
  BILL_YY VARCHAR2(4) NOT NULL,
  INV_DATE DATE,
  EVENT_SEQ NUMBER(2,0) NOT NULL,
  PACKATE_NAME VARCHAR2(60) NOT NULL,
  INVOICEMNY NUMBER(18,6),
  PACKAGE_PRICE NUMBER(18,6),
  ADJDISCMNY NUMBER(18,6),
  ADJOTHERMNY NUMBER(18,6),
  VAS_EXC_VAT NUMBER(18,6) NOT NULL,
  VAT_MNY NUMBER(18,6),
  VAS_MNY NUMBER(18,6),
  ACCOUNT_NO VARCHAR2(50) NOT NULL,
  BILLPERIOD VARCHAR2(22) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  USER_DTM DATE,
  USER_ID VARCHAR2(50),
  CDR_FILENAME VARCHAR2(300),
  CDR_ID VARCHAR2(22)
);

CREATE OR REPLACE PUBLIC SYNONYM SS_3BB_VDO FOR SETTLEMN.SS_3BB_VDO;

GRANT select, insert, update, delete on SETTLEMN.SS_3BB_VDO to SS_ADMIN;
GRANT select on SETTLEMN.SS_3BB_VDO to SS_QUERY;

CREATE INDEX IDX1_SS_3BB_VDO on SS_3BB_VDO (INVOICENO ASC, START_DATE ASC);
CREATE INDEX IDX2_SS_3BB_VDO on SS_3BB_VDO (PACKATE_NAME ASC);

ALTER TABLE settlemn.ss_master_sff_onspot
MODIFY FILE_NAME VARCHAR2(300);

ALTER TABLE settlemn.ss_master_sff_onspot
RENAME COLUMN user_name TO user_id;